### ISSUE TITLE
Masterize la feature

### ISSUE THREAD

**Issue by tdanel** [PyroTeam/gazebo-rcll#3]

**Comment by ValentinVERGEZ** [comment]
Ça veut dire quoi ?

**Comment by ValentinVERGEZ** [comment]
Ah, j'ai compris :-)

**Comment by tdanel** [comment]
Avoir une branche master, devel, et possiblement feature pour gripper
- si on a le courage et l'envie, l'envie d'avoir envie... de faire des trucs propres ;)

**Comment by ValentinVERGEZ** [comment]
Voir PR-#7. A fermer après intégration effective à `master`

**Comment by ValentinVERGEZ** [comment]
DONE
