### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by tdanel** [PyroTeam/gazebo-rcll#6]
Plugins "maison" propres et dans le dossier gazebo_rcll/plugins/pyro...

**Comment by ValentinVERGEZ** [comment]
Quels plugins ?

**Comment by tdanel** [comment]
Tous ! :P

**Comment by ValentinVERGEZ** [comment]
Ok. On n'a pas de plugin maison. Tu parles donc des plugins de sensors ?

**Comment by tdanel** [comment]
yep

**Comment by ValentinVERGEZ** [comment]
Ok dans `devel` depuis rework d'octobre
